### ISSUE TITLE
effects don't seem to take place until an event triggers

### ISSUE THREAD

**Issue by HalosGhost** [sdhand/x11fs#9]
To clarify what I mean,

When I `cat $X11FS/event` to watch events stream in, if I try to interrupt the stream by passing `SIGINT` through `^C`, the stream does not stop until another event happens.

Similarly, when I increase the border-width of a window (this is under `dwm`), the width effect does not take place until the window actually goes out of sight (e.g., by switching views or removing the window from the current tags) and is brought back.

Ideally, all effects should be immediate.

**Comment by sdhand** [comment]
I am aware of the issue with catting $X11FS/event, and am not sure I can fix it. When cat calls `read` it blocks in `get_events()` (which in calls `xcb_wait_for_event()` which blocks.) While cat is blocked on this read call it will not respond to `SIGINIT`, and I don't see much of a way round this. The window border problem sounds like dwm may be in some way conflicting with x11fs setting the border width. (If I understand the problem correctly, when you echo a number into`$X11FS/<winid>/border/width` the width doesn't change). Whilst I am planning to make x11fs work alongside window managers, it currently only works with 100% functionality when running standalone. Unfortunately making it work with every window manager will be nigh on impossible, due to the mess of standards that X window managers follow/don't follow. My current plan is to make a version of x11fs (or add a command line flag), to allow it to communicate with window managers following the ewmh standard. However there will still be incompatibilities with window managers such as DWM which don't implement ewmh.

**Comment by HalosGhost** [comment]
Ahh, so then these are two separate issues. Good to know.

Disregard the border issue; I do not expect x11fs to ever function completely correctly under reparenting WMs. As for the first, you could register your own signal handler for `SIGINT` to fail out, but I am not convinced that is a good idea, so this may not be fixable.
